#! /usr/bin/env zsh

# Get the directory where the script is located
SCRIPT_DIR=$(dirname "$0")
SCRIPT_DIR=$(cd "$SCRIPT_DIR" && pwd)

case "$1" in
    
    "queue")
	julia --project "$SCRIPT_DIR/queue.jl"
	;;
    
    "launch")
	julia --project "$SCRIPT_DIR/launch.jl" $2
	;;
    
    "extract")
	julia --project "$SCRIPT_DIR/extract.jl"
	;;
    
    *)
	echo "Usage: flow {queue|launch|extract}"
	;;
    
esac

