#!/usr/bin/env bash

# This script runs the 'flow launch' command in parallel for a specified number of times using GNU Parallel.

NUM="$1"

if [ -z "$NUM" ]; then
  echo "Usage: ./run_parallel.sh <number_of_parallel_processes>"
  exit 1
fi

# flow queue

mkdir -p ./data/logs

for (( i=1; i<=NUM; i++ ))
do
    echo flow launch ${i} '>>' ./data/logs/launch.jl_${i}.log >> parallel.tmp
done

cat parallel.tmp | nice -n 10 parallel
rm parallel.tmp